name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - dev
jobs:
  build_and_deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - name: Create .env file
        env:
          shipperApiUrl: ${{ vars.SHIPPER_API_URL }}
          loadApiUrl: ${{ vars.LOAD_API_URL }}
          transporterApiUrl: ${{ vars.TRANSPORTER_API_URL }}
          documentApiUrl: ${{ vars.DOCUMENT_API_URL }}
          driverApiUrl: ${{ vars.DRIVER_API_URL }}
          biddingApiUrl: ${{ vars.BIDDING_API_URL }}
          bookingApiUrl: ${{ vars.BOOKING_API_URL }}
          truckApiUrl: ${{ vars.TRUCK_API_URL }}
          gpsApiUrl: ${{ vars.GPS_API_URL }}
          buyGPSApiUrl: ${{ vars.BUY_GPS_API_URL }}
          mapKeyOld: ${{ vars.MAP_KEY_OLD }}"
          mapKeyNew: ${{ vars.MAP_KEY_NEW }}"
          mapKey: ${{ vars.MAP_KEY }}"
          rapidKey: ${{ vars.RAPID_KEY }}
          shareUrl: ${{ vars.SHARE_URL }}"
          routeHistoryApiUrl: ${{ vars.ROUTE_HISTORY_API_URL }}"
          traccarApi: ${{ vars.TRACCAR_API }}"
          traccarUser: ${{ vars.TRACCAR_USER }}"
          traccarPass: ${{ vars.TRACCAR_PASS }}"
          routeDataApiUrl: ${{ vars.ROUTE_DATA_API_URL}}"
          idfyAccountId: ${{ vars.IDFY_ACCOUNT_ID}}"
          idfyApiKey: ${{ vars.IDFY_API_KEY }}"
          idfyKey_id: ${{ vars.IDFY_KEY_ID }}"
          idfyOu_id: ${{ vars.IDFY_OU_ID }}"
          idfySecret_Key: ${{ vars.IDFY_SECRET_KEY }}"
          webHookUrl: ${{ vars.WEB_HOOK_URL }}"
          uidByPhoneNumber: ${{ vars.UID_BY_PHONE_NUMBER }}"
          installerApi: ${{ vars.INSTALLER_API }}"
          placeAutoCompleteProxy: ${{ vars.PLACE_AUTO_COMPLETE_PROXY }}"
          getUidByPhoneNumber: ${{ vars.GET_UID_BY_PHONE_NUMBER }}"
          getUidByMail: ${{ vars.GET_UID_BY_MAIL }}"
          getUid: ${{ vars.GET_UID }}"
          oneSignalApiKey: ${{ vars.ONE_SIGNAL_API_KEY }}"
          oneSignalAppId: ${{ vars.ONE_SIGNAL_APP_ID }}"
          fastTag: ${{ vars.FAST_TAG }}"
          vahanUrl: ${{ vars.VAHAN_URL }}"
          invoiceApiUrl: ${{ vars.INVOICE_API_URL }}"
          consentApiUrl: ${{ vars.CONSENT_API_URL }}"
          consentStatusUrl: ${{ vars.CONSENT_STATUS_URL }}"
          numVerifyApiUrl: ${{ vars.NUM_VERIFY_API_URL }}"
          accessKey: ${{ vars.ACCESS_KEY }}"
          ewayBill: ${{ vars.EWAY_BILL }}"
          ewayBillUser: ${{ vars.EWAY_BILL_USER }}"
          sendInviteEmailUrl: ${{ vars.SEND_INVITE_EMAIL_URL }}"
          encryptKey: ${{ vars.ENCRYPT_KEY }}"
          inviteEmails: ${{ vars.INVITE_EMAILS }}"
          deleteInvite: ${{ vars.DELETE_INVITE }}"
          inviteBaseUrl: ${{ vars.INVITE_BASE_URL }}"

      - name: Merge to branch
        run: |
          git checkout dev
      - name: Print .env file
        run: cat .env

      - run: flutter pub get
      - run: flutter build web

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: web-build
          path: build/web


      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SHIPPERWEBAPP }}'
          channelId: live
          projectId: shipperwebapp